import os
import re
import json
import base64
import asyncio
import httpx
from io import BytesIO
from fpdf import FPDF
from typing import Dict, Any, Tuple

# ── Load prompt template ──────────────────────────────────────────────────────
_PROMPT_PATH = os.path.join(os.path.dirname(__file__), "..", "prompts", "pdf_prompt.txt")
with open(_PROMPT_PATH, "r") as f:
    _PDF_TEMPLATE = f.read()

MAX_RETRIES   = 3
RETRY_DELAYS  = [5, 15, 30]


def _build_url(model: str) -> str:
    api_key = os.getenv("GEMINI_API_KEY", "")
    if not api_key:
        raise ValueError("GEMINI_API_KEY is not set.")
    return (
        f"https://generativelanguage.googleapis.com/v1beta/models/"
        f"{model}:generateContent?key={api_key}"
    )


async def _call_gemini(prompt: str, model: str) -> Dict[str, Any]:
    """Call Gemini and return parsed JSON structure."""
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.5, "maxOutputTokens": 3000},
    }
    url = _build_url(model)
    last_error = None

    for attempt in range(MAX_RETRIES):
        try:
            async with httpx.AsyncClient(timeout=45.0) as client:
                response = await client.post(url, json=payload)
                if response.status_code == 429:
                    await asyncio.sleep(RETRY_DELAYS[attempt])
                    last_error = "Rate limited"
                    continue
                response.raise_for_status()
                data = response.json()

            raw = (
                data.get("candidates", [{}])[0]
                .get("content", {})
                .get("parts", [{}])[0]
                .get("text", "")
            )
            cleaned = re.sub(r"```(?:json)?", "", raw).strip().strip("`")
            return json.loads(cleaned)

        except httpx.HTTPStatusError as e:
            if e.response.status_code == 429:
                await asyncio.sleep(RETRY_DELAYS[min(attempt, 2)])
                last_error = str(e)
                continue
            raise

    raise Exception(f"Gemini rate limit after {MAX_RETRIES} retries. {last_error}")


class _StyledPDF(FPDF):
    """Custom FPDF subclass with styled header/footer."""

    def header(self):
        # Thin purple top bar
        self.set_fill_color(79, 70, 229)
        self.rect(0, 0, 210, 3, "F")

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 170)
        self.cell(0, 10, f"Page {self.page_no()} — Generated by Prompt Intelligence Assistant", align="C")


def _build_pdf(doc: Dict[str, Any]) -> bytes:
    """Build a styled PDF from the structured document dict."""
    pdf = _StyledPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(20, 15, 20)
    pdf.add_page()

    # ── Title page area ──
    pdf.ln(8)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(26, 26, 80)
    pdf.multi_cell(0, 10, doc.get("title", "Document"), align="L")
    pdf.ln(2)

    if doc.get("subtitle"):
        pdf.set_font("Helvetica", "", 13)
        pdf.set_text_color(99, 102, 241)
        pdf.multi_cell(0, 7, doc["subtitle"], align="L")

    # Separator line
    pdf.ln(4)
    pdf.set_draw_color(99, 102, 241)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(8)

    # ── Sections ──
    for section in doc.get("sections", []):
        heading = section.get("heading", "")
        content = section.get("content", "")

        # Section heading
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(26, 26, 80)
        # Accent dot before heading
        pdf.set_fill_color(99, 102, 241)
        pdf.rect(20, pdf.get_y() + 1.5, 3, 7, "F")
        pdf.set_x(26)
        pdf.cell(0, 10, heading, ln=True)
        pdf.ln(1)

        # Section content
        pdf.set_font("Helvetica", "", 10.5)
        pdf.set_text_color(55, 65, 81)
        pdf.set_x(20)
        pdf.multi_cell(0, 6, content)
        pdf.ln(6)

    # ── Conclusion ──
    if doc.get("conclusion"):
        # Conclusion box
        pdf.set_fill_color(240, 240, 255)
        pdf.set_draw_color(99, 102, 241)
        pdf.set_line_width(0.3)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(79, 70, 229)
        pdf.cell(0, 8, "Conclusion", ln=True)
        pdf.ln(1)

        pdf.set_font("Helvetica", "", 10.5)
        pdf.set_text_color(55, 65, 81)
        pdf.multi_cell(0, 6, doc["conclusion"])

    return bytes(pdf.output())


async def generate_pdf(topic: str, model: str = "gemini-2.0-flash") -> Tuple[bytes, Dict]:
    """
    Main entry point — generate a styled PDF from a topic string.
    Returns (pdf_bytes, metadata_dict).
    """
    prompt = _PDF_TEMPLATE.format(topic=topic)
    doc    = await _call_gemini(prompt, model)
    pdf_bytes = _build_pdf(doc)

    metadata = {
        "title":       doc.get("title", "Document"),
        "section_count": len(doc.get("sections", [])),
        "page_count":  max(1, len(doc.get("sections", [])) // 2),
    }
    return pdf_bytes, metadata
